lr: 0.00025
aux_lr: 0.0001
gamma: 0.99
gae_lambda: 0.95
update_epochs: 4
minibatch_size: 256
clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
num_steps: 128 # Also known as rollout length
adam_eps: 1e-5
ep_info_buffer_size: 20